version: "3.9"
services:
  database:
    build: .docker/postgres
    container_name: app-database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "4321:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app-server
    volumes:
      - app-data:/home/app/thinking-out-loud
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      NODE_ENV: production
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOSTNAME: database

volumes:
  db-data:
  app-data:
